import {Montserrat_Underline  } from "next/font/google";
import "./globals.css";
import Header from "@/Compenets/Header";
import Footer from "@/Compenets/Footer";

const geistSans = Montserrat_Underline({
  subsets: ["latin"],
  variable: "--Montserrat_Underline",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
